export const GET_FLOURISH_DATA_REQUEST = "GET_FLOURISH_DATA_REQUEST";
export const GET_FLOURISH_DATA_SUCCESS = "GET_FLOURISH_DATA_SUCCESS";
export const GET_FLOURISH_DATA_FAILED = "GET_FLOURISH_DATA_FAILED";

export const DELETE_PHOTO_REQUEST = "DELETE_PHOTO_REQUEST";
export const DELETE_PHOTO_SUCCESS = "DELETE_PHOTO_SUCCESS";
export const DELETE_PHOTO_FAILED = "DELETE_PHOTO_FAILED";

export const ADD_PHOTO_REQUEST = "ADD_PHOTO_REQUEST";
export const ADD_PHOTO_SUCCESS = "ADD_PHOTO_SUCCESS";
export const ADD_PHOTO_FAILED = "ADD_PHOTO_FAILED";

export const RELOAD_GALLERY_REQUEST = "RELOAD_GALLERY_REQUEST";
export const RELOAD_GALLERY_SUCCESS = "RELOAD_GALLERY_SUCCESS";
export const RELOAD_GALLERY_FAILED = "RELOAD_GALLERY_FAILED";

export const RELOAD_TRACKING_REQUEST = "RELOAD_TRACKING_REQUEST";
export const RELOAD_TRACKING_SUCCESS = "RELOAD_TRACKING_SUCCESS";
export const RELOAD_TRACKING_FAILED = "RELOAD_TRACKING_FAILED";

export const ADD_TRACKING_REQUEST = "ADD_TRACKING_REQUEST";
export const ADD_TRACKING_SUCCESS = "ADD_TRACKING_SUCCESS";
export const ADD_TRACKING_FAILED = "ADD_TRACKING_FAILED";

export const DELETE_TRACKING_REQUEST = "DELETE_TRACKING_REQUEST";
export const DELETE_TRACKING_SUCCESS = "DELETE_TRACKING_SUCCESS";
export const DELETE_TRACKING_FAILED = "DELETE_TRACKING_FAILED";
