export const FETCH_FLOURISHES_REQUEST = "FETCH_FLOURISHES_REQUEST";
export const FETCH_FLOURISHES_SUCCESS = "FETCH_FLOURISHES_SUCCESS";
export const FETCH_FLOURISHES_FAILED = "FETCH_FLOURISHES_FAILED";

export const UPDATE_FLOURISHES_PARAMS = "UPDATE_FLOURISHES_PARAMS";

export const DELETE_FLOURISH_REQUEST = "DELETE_FLOURISH_REQUEST";
export const DELETE_FLOURISH_SUCCESS = "DELETE_FLOURISH_SUCCESS";
export const DELETE_FLOURISH_FAILED = "DELETE_FLOURISH_FAILED";
